Added known_hosts

diff --git a/cluster/apps/media/plex-meta-manager/helm-release.yaml b/cluster/apps/media/plex-meta-manager/helm-release.yaml
--- a/cluster/apps/media/plex-meta-manager/helm-release.yaml
+++ b/cluster/apps/media/plex-meta-manager/helm-release.yaml
@@ -30,10 +30,10 @@ spec:
               set -o nounset
               set -o errexit
               sleep 600000000m
-              if [ -z "${SECRET_GITEA_ACCESS_TOKEN}" ]; then
-                printf "%s - Error - Missing GITEA_TOKEN environment variable" "$(date -u)"
-                exit 1
-              fi
+              # if [ -z "${SECRET_GITEA_ACCESS_TOKEN}" ]; then
+              #   printf "%s - Error - Missing GITEA_TOKEN environment variable" "$(date -u)"
+              #   exit 1
+              # fi
               git clone --depth 1 "${SECRET_CONFIGS_URL}" /shared/Configs
               echo "Clone Complete"
               echo "Setting Perms"
@@ -45,7 +45,7 @@ spec:
               # Path will be /shared/Configs/Plex-Meta-Manager/config.yml
               mountPath: /shared
             - name: secret-volume
-              readOnly: true
+              # readOnly: true
               mountPath: "/root/.ssh"
           containers:
           - name: plex-meta-manager
